name: build
on:
  # push:
  #   branches:
  #     - master
  schedule:
    # Run this script every 1 hrs
    #  */m hr day month day_of_week
    - cron:  '0 */1 * * *'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Description Tag'  
jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: run
        run: |
          npm install --omit=dev
          npm run build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.6
        with:
          single-commit: true
          git-config-email: <>
          branch: gh-pages
          folder: dist
